# Architecture identifier.
arch = "aarch64"
# Platform identifier.
platform = "aarch64-phytium-pi"
# Platform family.
family = "aarch64-phytium-pi"

# Base address of the whole physical memory.
phys-memory-base = "0x8000_0000"
# Size of the whole physical memory.
phys-memory-size = "0x8000_0000" # 2G
# Base physical address of the kernel image.
kernel-base-paddr = "0x9010_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_9010_0000"
# kernel-base-vaddr = "0x9010_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
 phys-virt-offset = "0xffff_0000_0000_0000"
#phys-virt-offset = "0x0000_0000_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
  ["0x40000000","0x10000000"],#pcie ecam config
  ["0x50000000","0x08000000"],#pcie ecam io config
  ["0x58000000","0x28000000"],#pcie ecam mmio 32
  ["0x1000000000","0x10000000"],#pcie ecam mmio 64




  ["0x2800_C000", "0x1000"],      # UART 0
  ["0x2800_D000", "0x1000"],      # UART 1
  ["0x2800_E000", "0x1000"],      # UART 2
  ["0x2800_F000", "0x1000"],      # UART 3
  ["0x3000_0000","0x800_0000"],     #other devices
]
virtio-mmio-regions = []
# UART Address
uart-paddr = "0x2800_D000"
uart-irq = "24"

# GIC Address
gicd-paddr = "0x3080_0000"
gicc-paddr = "0x3080_1000"

# Base physical address of the PCIe ECAM space.
# pci-ecam-base = "0x31a00000"
pci-ecam-base = "0x4000_0000"
# End PCI bus number.
pci-bus-end = "0x7"
# PCI device memory ranges.
pci-ranges = [
  ["0x58000000", "0x80000000"],
  ["0x1000000000 ", "0x2000000000"]
]

# Size of the nocache memory region
nocache-memory-size = "0x30_0000"

